### ISSUE TITLE
Support prefiltering

### ISSUE THREAD

**Issue by wcjordan** [KamranAsif/evil-diff#1]
When working with a large object, we may want to revise against a partial object rather than the whole object.  It would be nice if we could revise against a partial and have evil-diff skip any cases not found in the partial.

In LiveDesign, we support something like this by passing a function which return true so that we skip any missing paths (unless they're an element in an array).  The paths argument in the example below is an array of separated path parts, e.g. ['bb','app','grid','cell','AssayCell'];
```
const dataAtPath = _.get(fullData, path);
const newPathState = bb.util.diff(partialToMergeIn, dataAtPath, paths => {
  if (_.isArray(_.get(partialToMergeIn, paths.slice(0, -1)))) {
    // Never skip arrays since they're difficult to handle
    return false;
  }
  return !_.has(partialToMergeIn, paths);
});

if (dataAtPath !== newPathState) {
  // Clone each node along path
  this.clonePath(path);
  _.set(fullData, path, newPathState);
}
```

Additionally, when working with a single monolithic data store, we often know we've only changed a few paths, and don't want to revise over the whole object for performance reasons.  This is pretty easy to implement in user space, and is what the clonePath work at the bottom of my code sample does.

**Comment by wcjordan** [comment]
Example case:
```
const partialToMergeIn = {
  "requestedFragments": {
    "active": {
      "1": {
        "id": "1",
        "live_report_id": "active",
        "frozen": true,
        "columns": [],
        "start": 0,
        "row_ids": null,
        "end": 200
      }
    }
  }
};
const path = "workspaces.ResultWorkspace.fragments";

let fullData = {
  "workspaces": {
    "ResultWorkspace": {
      "shortcutData": {},
      "fragments": {
        "requestedFragments": {},
        "cachedPages": <MAKE THIS A GIANT OBJECT>,
      }
    },
    "feedbackWorkspace": {
      "showFeedbackPanel": false
    },
    "plotTooltipsWorkspace": {
      "openTooltips": {
        "hoveredPoints": {},
        "hoveredTooltips": {}
      },
      "fragmentMap": {}
    },
  }
};
```

Expected output:
```
assertDeepEquals(fullData, {
  "workspaces": {
    "ResultWorkspace": {
      "shortcutData": {},
      "fragments": {
        "requestedFragments": {
          "active": {
            "1": {
              "id": "1",
              "live_report_id": "active",
              "frozen": true,
              "columns": [],
              "start": 0,
              "row_ids": null,
              "end": 200
            }
          }
        }
        "cachedPages": <MAKE THIS A GIANT OBJECT>,
      }
    },
    "feedbackWorkspace": {
      "showFeedbackPanel": false
    },
    "plotTooltipsWorkspace": {
      "openTooltips": {
        "hoveredPoints": {},
        "hoveredTooltips": {}
      },
      "fragmentMap": {}
    },
  }
};
```
and we shouldn't spend anytime walking or diffing against the cachedPages object.

**Comment by KamranAsif** [comment]
How will this handle delete?

Do we differentiate between prop missing & prop undefined:
eg.
source: {foo: 1, bar: 2}
revision1: {foo: 10} => {foo: 10, bar: 2}; //bar unchanged
revision2: {foo: 10, bar: undefined} =>{foo: 10} //bar removed

Does that sound acceptable

**Comment by wcjordan** [comment]
Sure that works for me.  Currently we'd delete a fragment with something like:
```
partialToMergeIn = undefined;
path = "workspaces.ResultWorkspace.fragments.requestedFragments.active";
```
and we have no desire to have objects with keys pointing to undefineds.
